

site_name: 'Banking Demo Docs'

nav:
  - Home: index.md
  - account service: account-service.md
  - portfolio service: portfolio-service.md
  - quote service: quote-service.md
  - techdocs: techdocs.md

plugins:
  - techdocs-core