pivotal:
  quotesService:
    name: quote-service
  userService:
    name: user-service  
  accountsService:
    name: account-service
  portfolioService:
    name: portfolio-service
  analyticsService:
    name: analytics-service
logging:
  level:
     com:
        vmware:
           tanzu: DEBUG
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN
spring:
  sleuth:
    sampler:
      probability: 1.0
