spring:
  application:
     name: portfolio-service
  jpa:
     hibernate:
        ddl-auto: update
  cloud:
    config:
      fail-fast: true
      retry:
        max-interval: 10000
        max-attempts: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
  instance:
    hostname: ${HOSTNAME}
    #nonSecurePort: 80
    #metadata-map:
    #  management:
    #    port: 80
info:
  build:
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#  metrics:
#    export:
#      wavefront:
#        api-token: ${WAVEFRONT_TOKEN}
#        uri: proxy://wf-proxy:2878
# logging:
#   level:
#     ROOT: DEBUG
wavefront:
  application:
    name: banking-demo
    service: portfolio-svc