#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service-deployment
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: quote-service
  replicas: 1
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
      - name: quote-service
        image: projects.registry.vmware.com/tanzu_meta_pocs/banking-demo/quote-service-dotnet:v0.0.0.1
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:8080;http://0.0.0.0:8090
        - name: Management__Port
          value: "8080"
        - name: eureka__client__serviceUrl
          value: "http://discovery-server/eureka"
        - name: Management__0__Tracing__exporter__zipkin__endpoint
          value: "http://wf-proxy:9411/api/v2/spans"
        - name: Management__2__metrics__1__export__wavefront__Uri
          value: "proxy://wf-proxy:2878"
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: #@ data.values.namespace
  labels:
    app: quote-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: quote-service
  type: #@ data.values.service.type