#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: projects.registry.vmware.com/tanzu_meta_pocs/banking-demo/user-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: spring.cloud.config.uri
          value: #@ "http://config-server."+ data.values.namespace + ".svc.cluster.local"
        - name: WAVEFRONT_TOKEN
          value: #@ data.values.wavefront.token
        - name: EUREKA_URL
          value: #@ "http://discovery-server."+ data.values.namespace + ".svc.cluster.local/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: #@ data.values.namespace
  labels:
    app: user-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-service
  type: #@ data.values.service.type