#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: portfolio-service
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
      - name: portfolio-service
        image: projects.registry.vmware.com/tanzu_meta_pocs/banking-demo/portfolio-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: spring.cloud.config.uri
          value: #@ "http://config-server."+ data.values.namespace + ".svc.cluster.local"
        - name: WAVEFRONT_TOKEN
          value: #@ data.values.wavefront.token
        - name: EUREKA_URL
          value: #@ "http://discovery-server."+ data.values.namespace + ".svc.cluster.local/eureka"
        - name: DEP_NS
          value:  #@ data.values.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: #@ data.values.namespace
  labels:
    app: portfolio-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: portfolio-service
  type: #@ data.values.service.type