eureka:
  instance:
    nonSecurePort: ${server.port}
logging:
  level:
     com:
        vmware:
           tanzu: DEBUG
        netflix: INFO
     org:
        springframework:
           web: INFO
           cloud: WARN
spring:
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
# disable the hystrix streaming on rabbit locally
hystrix:
  stream:
    queue:
      enabled: false
