info:
  component: Config Server
spring:
  application:
    name: configserver
  # profiles:
  #   active: native
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        # native:
        #   searchLocations: file:${user.dir}/../config-data
# If you want to point to the main git,
#  then comment out spring.profiles.active and spring.cloud.config.server.native
#  and uncomment spring.cloud.config.server.git
       git:
         uri: https://github.com/MoSehsah/bank-demo
         searchPaths: config-data
         default-label: main
         
management:
  context_path: /admin
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
server:
  port: 8888
# logging:
#   level:
#     ROOT: DEBUG
wavefront:
  application:
    name: banking-demo
    service: configserver
