#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  token: #@ base64.encode(data.values.wavefrontToken)
kind: Secret
metadata:
  creationTimestamp: null
  name: wavefront-secret
  namespace: observability-system